### ISSUE TITLE
authentication in application controller

### ISSUE THREAD

**Issue by aravindgd** [FSFTN/Pension-Tracker#7]
If you have

```
 before_filter :authenticate_user!
```

 in the application_controller then all the pages can be only viewed with logging in, is this the desired result?

**Comment by prashantbarca** [comment]
I think we need to add except here.

**Comment by aravindgd** [comment]
Except won't help much and make things complex. Add the before_filter to controllers where you need authentication alone not everywhere else and also change before_filter to before_action as the former is about to be deprecated.

**Comment by prashantbarca** [comment]
Okay... I just read the application_controller part! I thought this was in
some controller only! My bad! Yes... Horrible idea to put it in
application_controller.
